import '@testing-library/jest-dom';
import { vi } from 'vitest';

beforeEach(() => {
  vi.clearAllMocks();
});

export const mockGameState = {
  id: 'test-game-1',
  turn: 1,
  age: 'antiquity' as const,
  eraScore: 0,
  turnStartTimestamp: Date.now(),
  players: [],
  map: {
    width: 20,
    height: 12,
    seed: 'TEST123',
    tiles: [],
    resources: [],
    wonders: [],
  },
  cityStates: [],
  cityStateEnvoys: new Map(),
  tradeRoutes: [],
  religions: [],
  crises: [],
  barbarianCamps: [],
  greatPersons: [],
  victoryProgress: {
    domination: { controlledCapitals: 0, totalCapitals: 0, progress: 0 },
    science: { technologiesComplete: 0, totalTechnologies: 0, progress: 0 },
    culture: { tourists: 0, requiredTourists: 0, progress: 0 },
    religious: { citiesWithReligion: 0, totalCities: 0, progress: 0 },
    diplomatic: { votesWon: 0, requiredVotes: 4, progress: 0 },
    age: { objectivesCompleted: 0, totalObjectives: 3, progress: 0 },
  },
  settings: {
    mapSize: 'standard',
    mapType: 'continents',
    mapSeed: 'TEST123',
    difficulty: 'standard',
    gameSpeed: 'standard',
    aiCount: 2,
    cityStateCount: 8,
    victoriesEnabled: {
      domination: true,
      science: true,
      culture: true,
      religious: true,
      diplomatic: true,
      age: true,
    },
    barbarians: true,
    resources: 'standard',
    fogOfWar: true,
    quickCombat: false,
    gameVersion: '1.0.0',
  },
  cheats: {
    enabled: false,
    productionMultiplier: 1,
    goldMultiplier: 1,
    scienceMultiplier: 1,
    cultureMultiplier: 1,
    faithMultiplier: 1,
    foodMultiplier: 1,
    movementMultiplier: 1,
    combatMultiplier: 1,
    buildMultiplier: 1,
  },
  version: '1.0.0',
};

export const createMockTile = (x: number, y: number, terrain: string = 'grassland') => ({
  x,
  y,
  terrain: terrain as any,
  feature: null,
  resource: null,
  improvement: null,
  owner: null,
  units: [],
  visibility: 'hidden' as const,
});

export const createMockUnit = (id: string, type: string = 'warrior') => ({
  id,
  type,
  owner: 0,
  x: 0,
  y: 0,
  health: 100,
  maxHealth: 100,
  movement: 2,
  maxMovement: 2,
  strength: 16,
  strengthBase: 16,
  promotions: [],
  experience: 0,
  cargo: [],
  buildCharges: 0,
  hasActed: false,
  fortificationTurns: 0,
  isEmbarked: false,
  religion: null,
});

export const createMockCity = (id: string, name: string, population: number = 1) => ({
  id,
  name,
  owner: 0,
  population,
  x: 0,
  y: 0,
  buildQueue: [],
  currentProduction: null,
  foodStockpile: 0,
  foodForGrowth: population * 2 + 4,
  amenities: 2,
  amenitiesRequired: Math.ceil(population * 0.5),
  housing: 3,
  housingUsed: population,
  districtIds: [],
  workedTiles: [],
  specialistSlots: [],
  isOriginalCapital: true,
  garrison: null,
  turnFounded: 1,
  turnsOfGarrison: 0,
  liberationStatus: 'none' as const,
  wasFoundedBy: null,
  isBeingRazed: false,
  razeTurnsRemaining: 0,
});

export const createMockPlayer = (id: number, name: string = 'Test Player') => ({
  id,
  civilizationId: 'rome',
  leaderId: 'augustus',
  color: '#FFD700',
  name,
  cities: [],
  units: [],
  resources: {},
  technologies: new Set<string>(),
  civics: new Set<string>(),
  currentResearch: null,
  currentCivic: null,
  government: 'chiefdom' as const,
  policies: [],
  religion: null,
  score: 0,
  eraScore: 0,
  legacyObjectives: [],
  legacyObjectivesCompleted: new Set<string>(),
  isAlive: true,
  isAI: false,
  aiType: 'random' as const,
  grievances: new Map(),
  warWeariness: 0,
  relationship: new Map(),
});
